spring.application.name=mealtracker

spring.datasource.url=jdbc:postgresql://localhost:5432/mealtracker_db
spring.datasource.username=dmitriy
spring.datasource.password=banana19
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8080
spring.datasource.connection-properties=useUnicode=true;characterEncoding=UTF-8
# ????? ????????? Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.parameters.liquibase.runInTransaction=false
spring.liquibase.enabled=true
spring.liquibase.drop-first=false
spring.liquibase.default-schema=public
spring.liquibase.database-change-log-table=databasechangelog
spring.liquibase.database-change-log-lock-table=databasechangeloglock
spring.jpa.hibernate.ddl-auto=none


spring.jpa.show-sql=true

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

jwt.secret=yUkMhwoaWKUpwoYylQ5Uh1FURFJGnOrNBIs7//+LRUI=
#jwt.secret=superSecretKeyThatIsAtLeast32CharactersLongAndHasNoSpaces




# \u041E\u0442\u043A\u043B\u044E\u0447\u0438\u0442\u044C open-in-view (\u0443\u043B\u0443\u0447\u0448\u0430\u0435\u0442 \u043F\u0440\u043E\u0438\u0437\u0432\u043E\u0434\u0438\u0442\u0435\u043B\u044C\u043D\u043E\u0441\u0442\u044C)
spring.jpa.open-in-view=false

# \u041D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0438 Swagger/OpenAPI (\u0434\u043B\u044F \u0440\u0430\u0437\u0440\u0430\u0431\u043E\u0442\u043A\u0438 \u043E\u0441\u0442\u0430\u0432\u043B\u044F\u0435\u043C true)
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# \u041D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0430 \u0434\u0435\u043C\u043E-\u0434\u0430\u043D\u043D\u044B\u0445 (\u0432\u043A\u043B\u044E\u0447\u0430\u0435\u043C)
app.init-demo-data=true
app.demo.default-username=dmitriy


logging.level.root=INFO
logging.level.liquibase=DEBUG
logging.level.org.springframework.boot.autoconfigure.liquibase=DEBUG
logging.level.org.hibernate.SQL=DEBUG