spring.application.name=mealtracker

spring.datasource.url=jdbc:postgresql://localhost:5432/mealtracker_db
spring.datasource.username=dmitriy
spring.datasource.password=banana19

# ????? ????????? Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.sql
spring.liquibase.enabled=true
spring.liquibase.drop-first=false
spring.liquibase.default-schema=public
spring.liquibase.database-change-log-table=databasechangelog
spring.liquibase.database-change-log-lock-table=databasechangeloglock
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.hbm2ddl.auto=none

spring.jpa.show-sql=true

app.init-demo-data=true

logging.level.root=INFO
logging.level.liquibase=DEBUG
logging.level.org.springframework.boot.autoconfigure.liquibase=DEBUG
logging.level.org.hibernate.SQL=DEBUG